# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Graeme Arthur
email: graeme@graemearthur.com
description: > # this means to ignore newlines until "baseurl:"
Software engineer with a passion for building beautiful, well tested applications with clean code and maintainable architecture. Expert in iOS, TDD and agile development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://graemearthur.com" # the base hostname & protocol for your site
twitter_username: scottishgraeme
github_username:  graeme

# Build settings
markdown: kramdown
